In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
type(a)

numpy.ndarray

In [7]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [8]:
type(b)

numpy.ndarray

In [9]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [10]:
a.dtype

dtype('int64')

In [11]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [12]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
np.empty((2,3))

array([[6.92257358e-310, 2.33699849e-316, 6.92254381e-310],
       [6.92254380e-310, 6.92254380e-310, 6.92256393e-310]])

In [16]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [17]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [18]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [21]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [22]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [26]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [27]:
np.set_printoptions(threshold=np.nan)

In [28]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [29]:
c = a - b
c

array([20, 29, 38, 47])

In [30]:
b ** 2

array([0, 1, 4, 9])

In [31]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [32]:
a < 35

array([ True,  True, False, False])

In [33]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
A * B

array([[2, 0],
       [0, 4]])

In [34]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [35]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [36]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [37]:
b += a
b

array([[3.47215575, 3.49333825, 3.72135172],
       [3.48028057, 3.65053476, 3.39812395]])

In [38]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [39]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [40]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [41]:
c.dtype.name

'float64'

In [42]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [43]:
d.dtype.name

'complex128'

In [44]:
a = np.random.random((2,3))
a

array([[0.61463475, 0.33814904, 0.42095628],
       [0.53891208, 0.8042948 , 0.75731606]])

In [45]:
a.sum()

3.474263016418634

In [46]:
a.min()

0.3381490392055543

In [47]:
a.max()

0.804294796358413

In [48]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [50]:
b.min(axis=1)

array([0, 4, 8])

In [51]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [52]:
B = np.arange(3)
B

array([0, 1, 2])

In [53]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [54]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [55]:
C = np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

In [56]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [57]:
a[2]

8

In [58]:
a[2:5]

array([ 8, 27, 64])

In [59]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [60]:
for i in a:
    print(i ** (1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [62]:
def f(x,y):
    return 10 * x + y

b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [63]:
b[2,3]

23

In [64]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [65]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [67]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [68]:
b[-1]

array([40, 41, 42, 43])

In [69]:
 c = np.array( [[[  0,  1,  2],               
               [ 10, 12, 13]],
               [[100,101,102],
               [110,112,113]]])
c.shape

(2, 2, 3)

In [70]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [71]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [72]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [73]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
