In [1]:
import numpy as np

# 创建一维数组
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
array.shape

(20,)

In [3]:
array[3]

3

In [4]:
array[3] = 'Numpy'

ValueError: invalid literal for int() with base 10: 'Numpy'

In [5]:
# 创建二维数组
array = np.arange(20).reshape(4, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
array[3][4]

19

In [7]:
array.shape

(4, 5)

In [8]:
# 创建三维数组及更多维度
array = np.arange(27).reshape(3,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
array.shape

(3, 3, 3)

In [10]:
np.arange(10, 35, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

In [11]:
# use other numpy function
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((2,3))

array([[0.00000000e+000, 5.39489646e-317, 5.31020175e-317],
       [6.93514288e-310, 6.93514288e-310, 6.93511997e-310]])

In [14]:
np.full((2,2), 3)

array([[3, 3],
       [3, 3]])

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.linspace(0, 10, num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [17]:
# 从Python列表转换
array = np.array([4,5,6])
array

array([4, 5, 6])

In [18]:
list = [4,5,6]
list

[4, 5, 6]

In [20]:
type(list)

list

In [21]:
type(array)

numpy.ndarray

In [22]:
array = np.array([(1,2,3),(4,5,6)])
array.shape

(2, 3)

In [23]:
# 使用特殊的库函数
np.random.random((2,2))

array([[0.84436594, 0.42544788],
       [0.29411167, 0.38331316]])