In [4]:
import numpy as np

my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [5]:
# 形状
my_array.shape

(5,)

In [6]:
my_array[0]
my_array[1]

2

In [7]:
# 修改元素
my_array[0] = -1
my_array

array([-1,  2,  3,  4,  5])

In [8]:
# np.zeros np.ones
my_new_array = np.zeros((5))
my_new_array

array([0., 0., 0., 0., 0.])

In [10]:
# 随机数组
my_random_array = np.random.random((5))
my_random_array

array([0.70801636, 0.77688356, 0.12519768, 0.04352288, 0.49807944])

In [11]:
# 二维数组
my_2d_array = np.zeros((2,3))
my_2d_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
my_2d_array_new = np.ones((2,4))
my_2d_array_new

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
my_array = np.array([[4,5],[6,1]])
my_array[0][1]

5

In [14]:
my_array.shape

(2, 2)

In [15]:
# 打印一列
my_array_column_2 = my_array[:, 1]
my_array_column_2

array([5, 1])

In [17]:
a = np.array([[1.0,2.0],[3.0,4.0]])
b = np.array([[5.0,6.0],[7.0,8.0]])

sum = a + b
difference = a - b
product = a * b
quotient = a / b 
print('Sum = \n', sum)
print('Difference = \n', difference)
print('Product = \n', product)
print('Quotient = \n', quotient)

Sum = 
 [[ 6.  8.]
 [10. 12.]]
Difference = 
 [[-4. -4.]
 [-4. -4.]]
Product = 
 [[ 5. 12.]
 [21. 32.]]
Quotient = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
matrix_product = a.dot(b)
'Matrix Product = ', matrix_product

('Matrix Product = ', array([[19., 22.],
        [43., 50.]]))