In [1]:
import numpy as np

A = np.array([[1,-1,2],
              [3,2,0]])
A

array([[ 1, -1,  2],
       [ 3,  2,  0]])

In [2]:
v = np.array([[2],[1],[3]])
v

array([[2],
       [1],
       [3]])

In [3]:
# vT
v = np.transpose(np.array([2,1,3]))
v

array([2, 1, 3])

In [4]:
A[:, 1:2]

array([[-1],
       [ 2]])

In [5]:
col = A[:, 1:2]
col

array([[-1],
       [ 2]])

In [6]:
# dot
w = np.dot(A, v)
w

array([7, 8])

In [7]:
# numpy 求解方程组
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]]))

x = np.linalg.solve(A, b)
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [8]:
# 多元线性回归
# β = (XT X)-1 XT y
# (XT X) β = XT y

# Xt = np.transpose(X)
# XtX = np.dot(Xt, X)
# Xty = np.dot(Xt, y)
# beta = np.linalg.solve(XtX, Xty)

In [15]:
# 对Windsor房价数据集进行线性回归
import csv
import numpy as np

def readData():
    X = []
    y = []
    with open('./data/Housing.csv') as f:
        rdr = csv.reader(f)
        # Skip the header row
        next(rdr)
        # Read X and y
        for line in rdr:
            xline = [1.0]
            for s in line[2:6]:
                xline.append(float(s))
            X.append(xline)
            y.append(float(line[1]))
    return (X,y)

X0,y0 = readData()
# Convert all but the last 10 rows of the raw data to numpy arrays
d = len(X0)-10
X = np.array(X0[:d])
y = np.transpose(np.array([y0[:d]]))

# Compute beta
Xt = np.transpose(X)
XtX = np.dot(Xt,X)
Xty = np.dot(Xt,y)
beta = np.linalg.solve(XtX,Xty)
print(beta)

# Make predictions for the last 10 rows in the data set
for data,actual in zip(X0[d:],y0[d:]):
    x = np.array([data])
    prediction = np.dot(x,beta)
    print('prediction = '+str(prediction[0,0])+' actual = '+str(actual))

[[-4.41876979e+03]
 [ 5.43403018e+00]
 [ 2.64492693e+03]
 [ 1.74664109e+04]
 [ 7.89810381e+03]]
prediction = 102645.42909674905 actual = 82500.0
prediction = 70760.07818441579 actual = 83000.0
prediction = 97464.34037314806 actual = 84000.0
prediction = 96667.0682376042 actual = 85000.0
prediction = 105498.29494108135 actual = 85000.0
prediction = 96124.59288113232 actual = 91500.0
prediction = 102645.42909674905 actual = 94000.0
prediction = 102645.42909674905 actual = 103000.0
prediction = 86849.2214698665 actual = 105000.0
prediction = 69382.81058659124 actual = 105000.0
