In [1]:
import numpy as np

In [2]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [3]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [5]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [6]:
x.shape

(4,)

In [7]:
y.shape

(5,)

In [8]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [9]:
xx.shape

(4, 1)

In [10]:
y.shape

(5,)

In [11]:
(xx + y).shape

(4, 5)

In [12]:
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [13]:
x.shape

(4,)

In [14]:
z.shape

(3, 4)

In [15]:
(x + z).shape

(3, 4)

In [16]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [17]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b= np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])