In [1]:
import numpy as np

In [2]:
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [5]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [6]:
np.array([1,2,3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [7]:
z.astype(float)

array([0., 1., 2.])

In [8]:
np.int8(z)

array([0, 1, 2], dtype=int8)

In [9]:
z.dtype

dtype('uint8')

In [10]:
d = np.dtype(int)
d

dtype('int64')

In [11]:
np.issubdtype(d, int)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  """Entry point for launching an IPython kernel.


True

In [12]:
np.issubdtype(d, float)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  """Entry point for launching an IPython kernel.


False