In [2]:
import numpy as np
from io import BytesIO

In [12]:
data = "1, 2, 3\n4, 5, 6"
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
data = "  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [14]:
data = "123456789\n   4  7 9\n   4567 9"
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [15]:
data = "1, abc , 2\n 3, xxx, 4"
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=',', dtype='|S5', autostrip=True)

array([[b'1', b'abc', b'2'],
       [b'3', b'xxx', b'4']], dtype='|S5')

In [17]:
 data = """#
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""
np.genfromtxt(BytesIO(data.encode('utf-8')), comments="#", delimiter=",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [18]:
data = '\n'.join(str(i) for i in range(10))
np.genfromtxt(BytesIO(data.encode('utf-8')),)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.genfromtxt(BytesIO(data.encode('utf-8')), skip_header=3, skip_footer=5)

array([3., 4.])

In [20]:
data = "1 2 3\n4 5 6"
np.genfromtxt(BytesIO(data.encode('utf-8')), names="a, b, c", usecols=("a", "c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [21]:
np.genfromtxt(BytesIO(data.encode('utf-8')), names="a, b, c", usecols=("a, c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [24]:
data = BytesIO("1 2 3\n 4 5 6".encode('utf-8'))
np.genfromtxt(data, dtype=[(_, int) for _ in "abc"])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [25]:
data = BytesIO("1 2 3\n 4 5 6".encode('utf-8'))
np.genfromtxt(data, names="A, B, C")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [26]:
data = BytesIO("So it goes\n#a b c\n1 2 3\n 4 5 6".encode('utf-8'))
np.genfromtxt(data, skip_header=1, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [29]:
data = BytesIO("1 2 3\n 4 5 6".encode('utf-8'))
ndtype = [('a', int), ('b', int), ('c', int)]
names = ['A', 'B', 'C']
np.genfromtxt(data, names=names, dtype=ndtype)

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('A', '<i8'), ('B', '<i8'), ('C', '<i8')])

In [30]:
data = BytesIO("1 2 3\n 4 5 6".encode('utf-8'))
np.genfromtxt(data, dtype=(int, float, int))

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<i8')])

In [31]:
data = BytesIO("1 2 3\n 4 5 6".encode('utf-8'))
np.genfromtxt(data, dtype=(int, float, int), names='a')

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('a', '<i8'), ('f0', '<f8'), ('f1', '<i8')])

In [32]:
data = BytesIO("1 2 3\n 4 5 6".encode('utf-8'))
np.genfromtxt(data, dtype=(int, float, int), defaultfmt='var_%02i')

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_00', '<i8'), ('var_01', '<f8'), ('var_02', '<i8')])

In [33]:
convertfunc = lambda x: float(x.strip('%'))/100.
data = '1, 2.3%, 45.\n6, 78.9%, 0'
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=',', names=names)

array([(1., nan, 45.), (6., nan,  0.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [37]:
# np.genfromtxt(BytesIO(data), delimiter=',', names=names, converters={1: convertfunc})

In [38]:
np.genfromtxt(BytesIO(data), delimiter=',', names=names, converters={'p': convertfunc})

array([(1., nan, 45.), (6., nan,  0.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [40]:
data = "1, , 3\n 4, 5, 6"
convert = lambda x: float(x.strip() or -999)
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=',', converters={1: convert})

array([[   1., -999.,    3.],
       [   4.,    5.,    6.]])

In [41]:
data = "N/A, 2, 3\n4, ,???"
kwargs = dict(delimiter=",",
               dtype=int,
               names="a,b,c",
               missing_values={0:"N/A", 'b':" ", 2:"???"},
               filling_values={0:0, 'b':0, 2:-999})
np.genfromtxt(BytesIO(data.encode('utf-8')), **kwargs)

array([(0, 2,    3), (4, 0, -999)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])