In [50]:
import numpy as np

In [3]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [4]:
x[1]

('Fido', 3, 27.)

In [5]:
x['age']

array([9, 3], dtype=int32)

In [6]:
x['age'] = 5
x

array([('Rex', 5, 81.), ('Fido', 5, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [7]:
np.dtype([('x', 'f4'), ('y', np.float32), ('z', 'f4', (2,2))])

dtype([('x', '<f4'), ('y', '<f4'), ('z', '<f4', (2, 2))])

In [8]:
np.dtype([('x', 'f4'),('', 'i4'),('z', 'i8')])

dtype([('x', '<f4'), ('f1', '<i4'), ('z', '<i8')])

In [9]:
np.dtype('i8,f4,S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [10]:
np.dtype('3int8, float32, (2,3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [11]:
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [12]:
np.dtype({'names': ['col1', 'col2'],
          'formats': ['i4', 'f4'],
          'offsets': [0, 4],
          'itemsize': 12})

dtype({'names':['col1','col2'], 'formats':['<i4','<f4'], 'offsets':[0,4], 'itemsize':12})

In [14]:
np.dtype=({'col1': ('i1',0), 'col2': ('f4',1)})

In [3]:
d = np.dtype([('x', 'i8'), ('y', 'f4')])
d.names

('x', 'y')

In [4]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

In [5]:
def print_offsets(d):
    print('offsets:', [d.fields[name][1] for name in d.names])
    print('itemsize:', d.itemsize)

In [6]:
print_offsets(np.dtype('u1,u1,i4,u1,i8,u2'))

offsets: [0, 1, 2, 6, 7, 15]
itemsize: 17


In [7]:
print_offsets(np.dtype('u1,u1,i4,u1,i8,u2', align=True))

offsets: [0, 1, 4, 8, 16, 24]
itemsize: 32


In [8]:
np.dtype([(('my title', 'name'), 'f4')])

dtype([(('my title', 'name'), '<f4')])

In [9]:
np.dtype({'name': ('i4', 0, 'my title')})

dtype([(('my title', 'name'), '<i4')])

In [12]:
for name in d.names:
    print(d.fields[name][:2])

(dtype('int64'), 0)
(dtype('float32'), 8)


In [13]:
x = np.array([(1,2,3),(4,5,6)], dtype='i8,f4,f8')
x[1] = (7,8,9)
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [16]:
twofield = np.zeros(2, dtype=[('A', 'i4'), ('B', 'i4')])
onefield = np.zeros(2, dtype=[('A', 'i4')])
nostruct = np.zeros(2, dtype='i4')
nostruct[:] = twofield

ValueError: Can't cast from structure to non-structure, except if the structure only has a single field.

In [23]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'S3')])
b[:] = a
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'S3')])

In [24]:
x = np.array([(1,2),(3,4)], dtype=[('foo', 'i8'), ('bar', 'f4')])
x['foo']

array([1, 3])

In [25]:
x['foo'] = 10
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [26]:
y = x['bar']
y[:] = 10
x

array([(10, 10.), (10, 10.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [27]:
y.dtype, y.shape, y.strides

(dtype('float32'), (2,), (12,))

In [28]:
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])
a[['a', 'c']]

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('a', '<i4'), ('c', '<f4')])

In [29]:
a[['a', 'c']] = (2, 3)
a

array([(2, 0, 3.), (2, 0, 3.), (2, 0, 3.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [30]:
a[['a', 'c']] = a[['c', 'a']]

In [31]:
x = np.array([1,2.,3.], dtype='i,f,f')
scalar = x[0]
scalar

(1, 1., 1.)

In [32]:
type(scalar)

numpy.void

In [33]:
x = np.array([(1,2),(3,4)], dtype=[('foo', 'i8'),('bar', 'f4')])
s = x[0]
s['bar'] = 100
x

array([(1, 100.), (3,   4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [34]:
scalar = np.array([1,2.,3.], dtype='i,f,f')[0]
scalar[0]

1

In [35]:
scalar[1] = 4

In [36]:
scalar.item(), type(scalar.item())

((1, 4.0, 1.0), tuple)

In [37]:
a = np.zeros(2, dtype=[('a', 'i4'), ('b', 'i4')])
b = np.ones(2, dtype=[('a', 'i4'), ('b', 'i4')])
a == b

array([False, False])

In [38]:
recordarr = np.rec.array([(1,2.,'Hello'),(2,3.,'World'),], dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
recordarr.bar

array([2., 3.], dtype=float32)

In [39]:
recordarr[1:2]

rec.array([(2, 3., b'World')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [40]:
recordarr[1:2].foo

array([2], dtype=int32)

In [41]:
recordarr.foo[1:2]

array([2], dtype=int32)

In [42]:
recordarr[1].baz

b'World'

In [46]:
arr = np.array([(1,2.,'Hello'),(2,3.,'World')], dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
recordarr = np.rec.array(arr)

In [53]:
# arr = np.array([(1,2.,'Hello'),(2,3.,"World")], dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'a10')])
# recordarr = arr.view(dtype=dtype((np.record, arr.dtype)), type=np.recarray)

In [54]:
recordarr = arr.view(np.recarray)
recordarr.dtype

dtype((numpy.record, [('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]))

In [55]:
arr2 = recordarr.view(recordarr.dtype.fields or recordarr.dtype, np.ndarray)

In [56]:
recordarr = np.rec.array([('Hello', (1,2)),('World', (3,4))], dtype=[('foo', 'S6'),('bar',[('A', int),('B', int)])])

In [57]:
type(recordarr.foo)

numpy.ndarray

In [58]:
type(recordarr.bar)

numpy.recarray