In [13]:
import numpy as np

In [14]:
a = np.arange(12)
b = a
b is a

True

In [15]:
b.shape = 3, 4
a.shape

(3, 4)

In [16]:
def f(x):
    print(id(x))
    
id(a)

140601056144880

In [17]:
f(a)

140601056144880


In [18]:
c = a.view()
c is a

False

In [19]:
c.base is a

True

In [20]:
c.flags.owndata

False

In [21]:
c.shape = 2,6
a.shape

(3, 4)

In [22]:
c[0,4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [23]:
s = a[:, 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [24]:
d = a.copy()
d is a

False

In [25]:
a.base is a

False

In [26]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])