In [2]:
# quicksort
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    
    return quicksort(left) + middle + quicksort(right)

quicksort([3, 6, 8, 10, 1, 2, 1])

[1, 1, 2, 3, 6, 8, 10]

In [3]:
# Numbers
x = 3
type(x)

int

In [4]:
x + 1

4

In [5]:
x - 1

2

In [6]:
x * 2

6

In [7]:
x ** 2

9

In [9]:
x += 1
x

5

In [11]:
x *= 2
x

20

In [13]:
y = 2.5
type(y)

float

In [14]:
print(y, y + 1, y * 2, y ** 2)

2.5 3.5 5.0 6.25


In [15]:
# Booleans
t = True
f = False
type(t)

bool

In [16]:
t and f

False

In [17]:
t or f

True

In [18]:
not t

False

In [19]:
t != f

True

In [20]:
# String
hello = 'hello'
world = 'world'
hello

'hello'

In [21]:
len(hello)

5

In [24]:
hw = hello + ' ' + world
hw

'hello world'

In [26]:
hw12 = '%s %s %d' % (hello, world, 12)
hw12

'hello world 12'

In [28]:
s = 'hello'
s.capitalize()

'Hello'

In [29]:
s.upper()

'HELLO'

In [31]:
s.rjust(7)

'  hello'

In [32]:
s.center(7)

' hello '

In [33]:
s.replace('l', '(ell)')

'he(ell)(ell)o'

In [34]:
'  world  '.strip()

'world'

In [35]:
# Lists
xs = [3, 1, 2]
print(xs, xs[2])

[3, 1, 2] 2


In [36]:
xs[-1]

2

In [37]:
xs[2] = 'foo'
xs

[3, 1, 'foo']

In [38]:
xs.append('bar')
xs

[3, 1, 'foo', 'bar']

In [39]:
x = xs.pop()
print(x, xs)

bar [3, 1, 'foo']


In [40]:
# Slicing
nums = list(range(5))
nums

[0, 1, 2, 3, 4]

In [41]:
nums[2:4]

[2, 3]

In [42]:
nums[2:]

[2, 3, 4]

In [43]:
nums[:2]

[0, 1]

In [44]:
nums[:]

[0, 1, 2, 3, 4]

In [45]:
nums[:-1]

[0, 1, 2, 3]

In [47]:
nums[2:4]  = [8, 9]
nums

[0, 1, 8, 9, 4]

In [49]:
# Loops
animals = ['cat', 'dog', 'momkey']
for animal in animals:
    print(animal)

cat
dog
momkey


In [50]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d %s' % (idx + 1, animal))

#1 cat
#2 dog
#3 monkey


In [51]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)

squares

[0, 1, 4, 9, 16]

In [52]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
squares

[0, 1, 4, 9, 16]

In [53]:
nums = [0, 1, 2, 3, 4]
even_squares = [ x ** 2 for x in nums if x % 2 == 0]
even_squares

[0, 4, 16]

In [5]:
# Dict
d = {'cat': 'cute', 'dog': 'furry'}
d['cat']

'cute'

In [6]:
'cat' in d

True

In [7]:
d['fish'] = 'wet'
d['fish']

'wet'

In [8]:
d.get('monkey', 'N/A')

'N/A'

In [9]:
d.get('fish', 'N/A')

'wet'

In [10]:
del d['fish']

In [11]:
d.get('fish', 'N/A')

'N/A'

In [13]:
# Loops
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A spider has 8 legs
A person has 2 legs
A cat has 4 legs


In [15]:
d = { 'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A spider has 8 legs
A person has 2 legs
A cat has 4 legs


In [17]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
even_num_to_square

{0: 0, 2: 4, 4: 16}

In [18]:
# Sets
animals = {'cat', 'dog'}
'cat' in animals

True

In [19]:
'fish' in animals

False

In [21]:
animals.add('fish')

In [23]:
'fish' in animals

True

In [24]:
len(animals)

3

In [25]:
animals.remove('cat')

In [26]:
len(animals)

2

In [30]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: dog
#2: fish
#3: cat


In [32]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(50)}
nums

{0, 1, 2, 3, 4, 5, 6, 7}

In [34]:
d = {(x, x + 1): x for x in range(10)}
t = (5, 6)
type(t)

tuple

In [35]:
d[t]

5

In [36]:
d[(1, 2)]

1

In [37]:
# Functions
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
    
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [38]:
def hello(name, loud=False):
    if loud:
        print('HELLO %s' % name.upper())
    else:
        print('hello %s' % name)
        
hello('Bob')

hello Bob


In [39]:
hello('Fred', loud=True)

HELLO FRED


In [42]:
# Class
class Greeter(object):
    """
    Greeter
    """
    def __init__(self, name):
        self.name = name
        
    def greet(self, loud=False):
        if loud:
            print('HELLO %s' % self.name.upper())
        else:
            print('hello %s' % self.name)
            
g = Greeter('Fred')
g.greet()

hello Fred


In [43]:
g.greet(loud=True)

HELLO FRED


In [45]:
# Numpy Arrays
import numpy as np
a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [47]:
a.shape

(3,)

In [48]:
print(a[0], a[1], a[2])

1 2 3


In [49]:
a[0] = 5
a

array([5, 2, 3])

In [51]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
b.shape

(2, 3)

In [52]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [54]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [55]:
b = np.ones((1, 2))
b

array([[1., 1.]])

In [56]:
c = np.full((2, 2), 7)
c

array([[7, 7],
       [7, 7]])

In [58]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [59]:
e = np.random.random((2, 2))
e

array([[0.06145053, 0.18108682],
       [0.30720005, 0.17147614]])

In [62]:
# Slicing
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = a[:2, 1:3]
a[0, 1]

2

In [63]:
b[0, 0] = 77
a[0, 1]

77

In [64]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [65]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [67]:
col_r1 = a[:, 1]
col_r2 = a[1:2, :]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [68]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [69]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [70]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [71]:
print(a[[0, 0], [1, 1]])

[2 2]


In [72]:
print(np.array([a[0, 1], a[0, 1]]))

[2 4]


In [74]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
a = np.array([[1, 2], [3, 4], [5, 6]])
book_idx = (a > 2)
book_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [76]:
a[book_idx]

array([3, 4, 5, 6])

In [77]:
a[a > 2]

array([3, 4, 5, 6])

In [78]:
# Numpy datatype
x = np.array([1, 2])
x.shape

(2,)

In [79]:
x = np.array([1.0, 2.0])
x.dtype

dtype('float64')

In [80]:
x = np.array([1, 2], dtype=np.int64)
x.dtype

dtype('int64')